# Page settings
baseurl = "localhost:1313"
title = "Godisanang Youth Centre"
languageCode = "en-us"
theme = "hugo-elate-theme"

[params]
  
  custom_css = [ "css/theme.css" ]

  # Meta
  author = ""
  description = ""
  email = ""

  # Navigation
  [params.navigation]
    # brand = "GYEF"
    # img = "test.jpg"
    home = "Home"
    work = "Projects"
    testimonials = "GYEF Recognition"
    services = "About"
    about = "Team"
    contact = "Contact"

    # You can add custom links before or after the default links
    # Assign a weight to define the order
    
    # prepended links
    #[[menu.prepend]]
    #  url = "http://gohugo.io"
    #  name = "Hugo"
    #  weight = 10

    # postpended links
    #[[menu.postpend]]
    #  url = "http://gohugo.io"
    #  name = "External link"
    #  weight = 10
  
  # Hero section
  [params.hero]
    title = "Godisanang Youth Centre"
    subtitle = 'Lorem ipsum dolor sit amet consectetur, adipisicing elit. Distinctio nulla, quibusdam tenetur quaerat optio at ducimus voluptatum odio doloremque. Voluptatibus id tenetur sit a explicabo excepturi ullam eligendi amet, error provident omnis'
 
  # Intro section
  # Available icons: http://simplelineicons.com/
  [params.intro]

  [[params.intro.item]]
    title = "Education"
    description = "We aim to take part in educational development in our country, formally and informally, through hosting programs that advance the improvement of education and better access to educational opportunities and tertiary"
    url = "#"
    button = "more"
    icon = "icon-bulb"
    img = "test.jpg"

  [[params.intro.item]]
    title = "Entrepreneurship"
    description = "We aim at promoting entrepreneurial participation while encouraging the usage of entrepreneurship as a tool to fight crime and unemployment. This is to be achieved through hosting programs that promote entrepreneurship and entrepreneurial education"
    url = "#"
    button = "more"
    icon = "icon-rocket"
    img = "img_10.jpg"

  [[params.intro.item]]
  title = "Talent Establishment"
  description = "Talent is one of the most things that are taken for-granted when it comes to youth development. With much observation lot of young people have talents which tend to not be used as much because there are lack of opportunities"
  url = "#"
  button = "more"
  icon = "icon-wrench"
  img = "img_8.jpg"

  [params.intro.video]
    enable = true
    title = "Godisanang Information & Computer Centers"
    icon = "icon-play2"
    url = "https://www.youtube.com/watch?v=nYJTWtT_YVU&list=RDnYJTWtT_YVU&start_radio=1"


  # Work section
  [params.work]
    enable = true
    title = "What We Are About"
    description = "We strive to see the youth having equal access to sufficient information and opportunities that enable them to have access to a brighter future."
    # footertext = '** Demo images from <a href="http://plmd.me/" target="_blank">plmd.me</a>'

    [[params.work.row]]
      img = "work_1.jpg"
      alt = "Image2"
      title = "Project 1"
      subtitle = "Project 1"

    [[params.work.row]]
      img = "work_2.jpg"
      alt = "Image2"
      title = "Project 2"
      subtitle = "Project 2"

    [[params.work.row]]
      img = "work_3.jpg"
      alt = "Image3"
      title = "Project 3"
      subtitle = "Project 3"

    [[params.work.row]]
      img = "work_4.jpg"
      alt = "Image4"
      title = "Project 4"
      subtitle = "Project 4"

    [[params.work.row]]
      img = "work_5.jpg"
      alt = "Image5"
      title = "Project 5"
      subtitle = "Project 5"

    [[params.work.row]]
      img = "work_6.jpg"
      alt = "Image6"
      title = "Project 6"
      subtitle = "Project 3"

  # Testimonials section
  [params.testimonials]
    enable = true
    title = "GYEF Recognition"
    description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Distinctio null"

    [[params.testimonials.item]]
      quote = " Meet Ms Lerato Moloelang (12) <br/><br/>Lerato is a one of South Africa’s youngest writers. Residing in Orlando East, Soweto, this grade 7 twelve-year old has already published a book titled ‘Dreams Come through’ which is aimed at empowering and uplifting her peers. Her books sells at R150 a copy..."

      person = 'Author: Dreams Come true <span class="subtext">#GYEFRecognitions</span>'
      img = "person1.jpg"
      alt = "Person1"

    [[params.testimonials.item]]
      quote = "Meet Dr Thandeka Ngcobo <br/><br/>Dr Thandeka Ngcobo is a 24 year old young lady from Ixopo in a small village called Hluthankungu. She grew up loving education and have always wanted to be a doctor when she grows up..."
      person = 'MBChB, University of KwaZulu-Nata</a> <span class="subtext">#GYEFRecognition</span>'
      img = "person2.jpg"
      alt = "Person2"

    [[params.testimonials.item]]
      quote = " Meet Ms Lerato Moloelang (12) <br/><br/>Lerato is a one of South Africa’s youngest writers. Residing in Orlando East, Soweto, this grade 7 twelve-year old has already published a book titled ‘Dreams Come through’ which is aimed at empowering and uplifting her peers. Her books sells at R150 a copy..."

      person = 'Author: Dreams Come true <span class="subtext">#GYEFRecognitions</span>'
      img = "person3.jpg"
      alt = "Person3"
    



  # Services section
  [params.services]
    enable = true
    title = "About Us"
    description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Distinctio nulla, quibusdam tenetur quaerat optio at ducimus voluptatum odio doloremque"

    [[params.services.item]]
      title = "Vision"
      description = "GYEF – To see the youth having equal access to sufficient information and opportunities that enable them to have access to a brighter future. **Uplifting the African Youth**"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Mission"
      description = "To help as much youth as possible access information and opportunities they need to empower themselves and fight poverty through hosting programs and establishing partnerships that ensure to advance the course"
      icon = "icon-anchor"

    [[params.services.item]]
      title = "Goals"
      description = "To deliver cost effective, impactful, and competent capacity building programs to disadvantaged communities particularly the youth"
      icon = "icon-anchor"

      [[params.services.item]]
      title = "Objectives"
      description = " >To raise awareness, understanding and knowledge on entrepreneurship to the disadvantaged communities<br/>To provide opportunities that enable the youth to use their talents to better their conditions and escape poverty <br/> To make campaigns that encourage more entrepreneurial participation and promote independence among the community members <br/> To host educational programs that promote health awareness among community members especially the youth To help raise funds to build facilities like libraries, youth centres and sports facilities for the youth"
      icon = "icon-anchor"

  # About section
  [params.about]
    enable = true
    title = "Executive Board Members"
    description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Distinctio nulla, quibusdam tenetur quaerat optio at ducimus voluptatum odio doloremque"

    [[params.about.item]]
      name = "Jabulane Tshabalala"
      position = "CEO &amp; Founder"
      description = "Jabulane is from Bodibe village North West Procince and strongly believes that through empowering the youth with opportunities and information we stand a better opportunity to build an inclusive sustainable economy..."
      img = "person1.jpg"
      alt = "Person1"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-linkedin", "#"]
      ]

    [[params.about.item]]
      name = "Bafana Tshabalala"
      position = "COO &amp; Co-Founder"
      description = "I believe that empowering young people with knowledge is the best strategy to tackle the issues facing our country currently, since we are the future. Like a wise man once uttered,that <cite> knowledge is power</cite>, with that we can ensure that our future as a country is bright"
      img = "person2.jpg"
      alt = "Person2"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-github", "#"]
      ]

    [[params.about.item]]
      name = "Lerato Nyokong"
      position = "Executive Secretary"
      description = "Lerato Nyokong has a chemical engineering graduate from the University of Witswatersrand. She is the CEO of Nyokong Hygiene. Lerato believes in developing young women so that can be empowered and leaders in their communities"
      img = "person3.jpg"
      alt = "Person3"
      social = [
        ["icon-twitter", "#"],
        ["icon-facebook", "#"],
        ["icon-dribbble", "#"]
      ]      

  # Counters section
  [params.counters]
    enable = false
    title = "Stats"
    background = "full_image_1.jpg"

    [[params.counters.item]]
      description = "Finished projects"
      icon = "icon-briefcase"
      from = 0
      to = 89
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Lines of code"
      icon = "icon-code"
      from = 0
      to = 2343409
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Cups of coffee"
      icon = "icon-cup"
      from = 0
      to = 1302
      interval = 50
      speed = 5000

    [[params.counters.item]]
      description = "Happy clients"
      icon = "icon-people"
      from = 0
      to = 52
      interval = 50
      speed = 5000

  # Contact section
  [params.contact]
    enable = true
    map = true
    form = true
    title = "Get in touch"
    description = "Lorem ipsum dolor sit amet consectetur, adipisicing elit. Distinctio null"
    
    # Available icons: http://simplelineicons.com/
    details = [
        ["icon-home", "1234 Palm Springs <br> Sebokeng, <br> Gauteng"],
        ["icon-phone", "(123) 465-6789"],
        ["icon-envelope", "info@gyef.co.za"],
        #["icon-globe", '<a href="http://freehtml5.co/" target="_blank">freehtml5.co</a>']
      ]

    name = "Name"
    email = "Email"
    phone = "Phone"
    message = "Message"
    button = "Send message"

  # Footer section
  [params.footer]
    enable = true
    copyright = '&copy; Godisanang Youth Centre. All Rights Reserved. <br>'
    links = [
        ["icon-twitter", "#twitter"],
        ["icon-facebook", "#facebook"],
        ["icon-youtube", "#youtube"]
      ]
